### ISSUE TITLE
Bootstrap configuration

### ISSUE THREAD

**Issue by zksadj** [holaplex/indexer#473]
Hi,

I'm trying to setup an indexer.
My validator has the following configuration:
```
exec solana-validator \
    --identity /home/sol/validator-keypair.json \
    --vote-account /home/sol/vote-account-keypair.json \
    --known-validator dv1ZAGvdsz5hHLwWXsVnM94hWf1pjbKVau1QVkaMJ92 \
    --known-validator dv2eQHeP4RFrJZ6UeiZWoc3XTtmtZCUKxxCApCDcRNV \
    --known-validator dv4ACNkpYPcE3aKmYDqZm9G5EB3J4MRoeE7WNDRBVJB \
    --known-validator dv3qDFk1DTF36Z62bNvrCXe9sKATA6xvVy6A798xxAS \
    --only-known-rpc \
    --ledger /var/lib/data/sol/ledger \
    --log /var/lib/data/sol/validator.log \
    --rpc-port 8899 \
    --dynamic-port-range 8000-8020 \
    --entrypoint entrypoint.devnet.solana.com:8001 \
    --entrypoint entrypoint2.devnet.solana.com:8001 \
    --entrypoint entrypoint3.devnet.solana.com:8001 \
    --entrypoint entrypoint4.devnet.solana.com:8001 \
    --entrypoint entrypoint5.devnet.solana.com:8001 \
    --expected-genesis-hash EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG \
    --wal-recovery-mode skip_any_corrupted_record \
    --limit-ledger-size \
    --geyser-plugin-config /var/lib/data/sol/config.json
```

My config.json file for the geyser plugin is the following:
```
{
  "libpath": "/home/ubuntu/indexer/target/debug/libholaplex_indexer_rabbitmq_geyser.so",
  "amqp": {
    "network": "devnet",
    "address": "amqp://127.0.0.1:5672"
  },
  "jobs": {
    "limit": 16
  },
  "metrics": {
   "config": "host="
  },
  "accounts": {
    "owners": [
      "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
      "vau1zxA2LbssAUEF7Gpw91zMM1LvXrvpzJtmZ58rPsn",
      "auctxRXPeJoc4817jDhf4HbjnhEcr1cCXenosMhK5R8",
      "p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98",
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
      "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
      "grphSXQnjAoPXSG5p1aJ7ZFw2A1akqP3pkXvjfbSJef",
      "cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ",
      "namesLPneVptA9Z5rqUDD9tMTWEJwofgaYwp8cawRkX",
      "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM",
      "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR",
      "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE",
      "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp",
      "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw",
      "Govz1VyoyLD5BL6CSCxUJLVLsQHRwjfFj1prNsdNg5Jw",
      "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH"
    ],
    "startup": false
  },
  "instructionPrograms": []
}
```

My rabbitMQ node is launched as a part of a modified `docker-compose.yml` file provided in the repo:
```
version: '3.8'
services:
  db:
    image: postgres:14.1
    container_name: holaplex_indexer.dev_db
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWD}
    volumes:
      - db_data:/var/lib/postgresql/data
    network_mode: host
  rabbitmq:
    image: rabbitmq:3.10.1
    container_name: rabbitmq
    network_mode: host
    
volumes:
  db_data:
    driver: local
    name: holaplex_indexer.dev_db_data
```
... which I run with `./docker-compose.sh up -d`.

Upon launching my validator, I get the following error in the logs:
```
ERROR solana_core::validator] Failed to load the Geyser plugin: PluginLoadError("Failed to load the plugin library: \"/home/ubuntu/indexer/target/debug/libholaplex_indexer_rabbitmq_geyser.so\", error: Custom(InvalidQueueType(\"Debug builds must specify a unique debug suffix for all AMQP names\"))")
```

My Rust isn't the best and this isn't documented anywhere so I'm having a bit of hard time understanding what I am doing wrong here.
I see the error message comes from [here](https://github.com/holaplex/indexer/blob/8627de79ef57c01c2ae363a292f07a596fcb4c9f/crates/rabbitmq/src/suffix.rs#L62) but how do I indicate a suffix from the config.json file?
Thank you in advance for the answers!
